export const PLAYLIST_LIST_REQUEST = 'PLAYLIST_LIST_REQUEST';
export const PLAYLIST_LIST_SUCCESS = 'PLAYLIST_LIST_SUCCESS';
export const PLAYLIST_LIST_FAIL = 'PLAYLIST_LIST_FAIL';

export const PLAYLIST_ADD_SONG_SUCCESS = 'PLAYLIST_ADD_SONG_SUCCESS'; 
export const PLAYLIST_ADD_SONG_FAIL = 'PLAYLIST_ADD_SONG_FAIL';

export const PLAYLIST_DETAILS_REQUEST = 'PLAYLIST_DETAILS_REQUEST';
export const PLAYLIST_DETAILS_SUCCESS = 'PLAYLIST_DETAILS_SUCCESS';
export const PLAYLIST_DETAILS_FAIL = 'PLAYLIST_DETAILS_FAIL';
